SOURCES = [
    {
        "id": "bbc-arabic",
        "name": "بي بي سي عربي",
        "name_en": "BBC Arabic",
        "type": "rss",
        "url": "https://feeds.bbci.co.uk/arabic/rss.xml",
        "category": "دولية",
    },
    {
        "id": "france24-arabic",
        "name": "فرانس 24 عربي",
        "name_en": "France 24 Arabic",
        "type": "rss",
        "url": "https://www.france24.com/ar/rss",
        "category": "دولية",
    },
    {
        "id": "dw-arabic",
        "name": "DW عربي",
        "name_en": "DW Arabic",
        "type": "rss",
        "url": "https://rss.dw.com/rdf/rss-ar-all",
        "category": "دولية",
    },
    {
        "id": "rt-arabic",
        "name": "RT عربي",
        "name_en": "RT Arabic",
        "type": "rss",
        "url": "https://arabic.rt.com/rss/",
        "category": "دولية",
    },
    {
        "id": "sana",
        "name": "سانا (سوريا)",
        "name_en": "SANA Syria",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Asana.sy&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "spa",
        "name": "واس (السعودية)",
        "name_en": "SPA Saudi Arabia",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Aspa.gov.sa&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "wam",
        "name": "وام (الإمارات)",
        "name_en": "WAM UAE",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Awam.ae&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "qna",
        "name": "قنا (قطر)",
        "name_en": "QNA Qatar",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Aqna.org.qa&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "kuna",
        "name": "كونا (الكويت)",
        "name_en": "KUNA Kuwait",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Akuna.net.kw&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "mena",
        "name": "مينا (مصر)",
        "name_en": "MENA Egypt",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Amena.org.eg&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "petra",
        "name": "بترا (الأردن)",
        "name_en": "Petra Jordan",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Apetra.gov.jo&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "wafa",
        "name": "وفا (فلسطين)",
        "name_en": "WAFA Palestine",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Awafa.ps&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "ina",
        "name": "الوكالة العراقية (العراق)",
        "name_en": "INA Iraq",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Aina.iq&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "ona",
        "name": "العمانية (عُمان)",
        "name_en": "ONA Oman",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Aomannews.gov.om&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "suna",
        "name": "سونا (السودان)",
        "name_en": "SUNA Sudan",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Asuna-sd.net&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "nna",
        "name": "الوطنية اللبنانية (لبنان)",
        "name_en": "NNA Lebanon",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Anna-leb.gov.lb&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "aa",
        "name": "الأناضول (تركيا)",
        "name_en": "Anadolu Agency",
        "type": "google",
        "url": "https://news.google.com/rss/search?q=source%3Aaa.com.tr&hl=ar&gl=SA&ceid=SA:ar",
        "category": "وكالة رسمية",
    },
    {
        "id": "aa-direct",
        "name": "الأناضول مباشر (تركيا)",
        "name_en": "Anadolu Agency Arabic",
        "type": "rss",
        "url": "https://www.aa.com.tr/ar/rss",
        "category": "وكالة رسمية",
    },
]